#if ((UNITY_SWITCH || UNITY_XBOXONE) && !UNITY_EDITOR) || GS_FORCE_NATIVE_PLATFORM

//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace GameSparksNative.detail {

class GameSparksNativePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionCallbacks_GameSparksNative")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="SWIGRegisterExceptionCallbacks_GameSparksNative")]
  #endif
    public static extern void SWIGRegisterExceptionCallbacks_GameSparksNative(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_GameSparksNative")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_GameSparksNative")]
  #endif
    public static extern void SWIGRegisterExceptionCallbacksArgument_GameSparksNative(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionDelegate))]
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
      [AOT.MonoPInvokeCallback (typeof (ExceptionArgumentDelegate))]
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_GameSparksNative(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_GameSparksNative(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(GameSparksNativePINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(GameSparksNativePINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterStringCallback_GameSparksNative")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="SWIGRegisterStringCallback_GameSparksNative")]
  #endif
    public static extern void SWIGRegisterStringCallback_GameSparksNative(SWIGStringDelegate stringDelegate);

      [AOT.MonoPInvokeCallback (typeof (SWIGStringDelegate))]
    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_GameSparksNative(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static GameSparksNativePINVOKE() {
  }


  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_Result_getType___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_Result_getType___")]
  #endif
  public static extern int NativeWebSocket_Result_getType(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_Result_getMessage___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_Result_getMessage___")]
  #endif
  public static extern string NativeWebSocket_Result_getMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_delete_NativeWebSocket_Result___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_delete_NativeWebSocket_Result___")]
  #endif
  public static extern void delete_NativeWebSocket_Result(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_new_NativeWebSocket___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_new_NativeWebSocket___")]
  #endif
  public static extern global::System.IntPtr new_NativeWebSocket();

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_delete_NativeWebSocket___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_delete_NativeWebSocket___")]
  #endif
  public static extern void delete_NativeWebSocket(global::System.Runtime.InteropServices.HandleRef jarg1);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GSExternalOpen___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GSExternalOpen___")]
  #endif
  public static extern void NativeWebSocket_GSExternalOpen(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, string jarg4);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GSExternalClose___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GSExternalClose___")]
  #endif
  public static extern void NativeWebSocket_GSExternalClose(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GSExternalSend___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GSExternalSend___")]
  #endif
  public static extern void NativeWebSocket_GSExternalSend(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_Update___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_Update___")]
  #endif
  public static extern bool NativeWebSocket_Update(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  #if (UNITY_IPHONE || UNITY_SWITCH || UNITY_XBOX360) && !UNITY_EDITOR
    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GetNextResult___")]
  #else
    [global::System.Runtime.InteropServices.DllImport("GameSparksNative", EntryPoint="CSharp_GameSparksNativefdetail_NativeWebSocket_GetNextResult___")]
  #endif
  public static extern global::System.IntPtr NativeWebSocket_GetNextResult(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}


#endif